### ISSUE TITLE
Extended ACLs missing

### ISSUE THREAD

**Issue by cjreyn** [arista-eosplus/pyeapi#108]
Extended ACLs are not supported. Will they ever be?

**Comment by phil-dileo** [comment]
Hi! We're in the planning stages for the next release and can try to get this into it.  Will keep you posted.

**Comment by cjreyn** [comment]
@phil-dileo thanks! I'm also missing a way to determine which ACL is applied to which interface. Currently I'm using the enable command 'show ip access-lists summary | json' and parsing the json to figure this out. I'm not sure which api call this might be good to add to.
