### ISSUE TITLE
`expandAlias` arg for `run_commands`

### ISSUE THREAD

**Issue by mirceaulinic** [arista-eosplus/pyeapi#126]
Hello,

It looks like the Command API provides support to expand aliases:

![expandalias](https://cloud.githubusercontent.com/assets/16694679/22107375/4ecc7766-de45-11e6-94d8-3bd69844068b.png)

However, this feature does not seem to be supported by the existing `run_commands` method: https://github.com/arista-eosplus/pyeapi/blob/master/pyeapi/client.py#L633

Is there any other possibility to run aliases through eAPI?

Thanks,
Mircea

**Comment by phil-dileo** [comment]
@mharista

**Comment by mharista** [comment]
Hi @mirceaulinic,

Currently you can not run aliases through eAPI using pyeapi. Your screenshot example looks like it would work with the autoComplete parameter and you can use this now with pyeapi by sending autoComplete=True to the execute method of the EapiConnection object.

```
import pyeapi
node = pyeapi.connect(username=[user], password=[password], host=[host])
output = node.execute(['sh ver'], autoComplete=True)
```

I'll work on adding the support for autoComplete with the run_commands method in addition to adding support for the expandAliases parameter. If you need to run using the expandAlias parameter before I have the updates in pyeapi you can use the jsonrpclib library in the below format.

```
from jsonrpclib import Server
node = Server('https://[user]:[password]@[host]/command-api')
output = node.runCmds(version=1, cmds=['ALIASCOMMAND'], format='json', expandAliases=True)
```

**Comment by mirceaulinic** [comment]
Thanks very much for clarifying this @mharista!
