### ISSUE TITLE
API path is hardcoded in EapiConnection.send()

### ISSUE THREAD

**Issue by bewing** [arista-eosplus/pyeapi#129]
Not sure if this is intended, but no matter what path is specified if calling HttpsEapiConnection directly, send() has /command-api hardcoded, instead of using self.transport.path

**Comment by dathelen** [comment]
@bewing 

Thanks for bringing this up. We will look into fixing this.   Just curious did you have a custom endpoint that you were trying to hit on an EOS node?

**Comment by bewing** [comment]
@dathelen 

I was actually playing around with a non-EOS endpoint that did have a different endpoint, but did use a runCmd JSON-RPC call.

The other use case I could see is a single reverse proxy distributing API calls to different switches depending on URL, as a kind of "jump-host"

**Comment by mharista** [comment]
Release Notes:
Updated the previously hardcoded path to /command-api in the EAPI connection to use the transport objects path.
