### ISSUE TITLE
Execute does not work well with long running commands

### ISSUE THREAD

**Issue by bobbywatson3** [arista-eosplus/pyeapi#138]
When executing a long-running task, a ConnectionError is intermittently raised. From the python console:

```python
eapi = pyeapi.connect(transport='http', host='172.20.1.6', username='user', password='pass')
cmds = ['enable', 'routing-context vrf management', 'copy http://172.20.1.4:8080/images/eos/EOS-4.18.1F.swi flash:']

eapi.execute(commands=cmds, encoding='json')
{u'jsonrpc': u'2.0', u'result': [{}, {}, {u'messages': [u'Copy completed successfully.']}], u'id': u'4542156176'}

eapi.execute(commands=cmds, encoding='json')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/bwatson/Projects/aeon-ztps/venv/lib/python2.7/site-packages/pyeapi/eapilib.py", line 490, in execute
    response = self.send(request)
  File "/Users/bwatson/Projects/aeon-ztps/venv/lib/python2.7/site-packages/pyeapi/eapilib.py", line 423, in send
    raise ConnectionError(str(self), 'unable to connect to eAPI')
ConnectionError: unable to connect to eAPI
```

The first copy completed without issue. The second raised a connection error.

**Comment by bobbywatson3** [comment]
I believe there is a timeout happening somewhere. Sometimes this will run for almost 60 seconds and complete. Sometimes it will run for an extended time and fail. If this is a timeout while waiting for the command to complete, it would be great if we could increase the timeout. It would also be great if there was an exception that better described what happened. The 'unable to connect to eAPI' message is false in this instance.

**Comment by mharista** [comment]
Hi @bobbywatson3,

I'll take a look into this. I'll hopefully get to it this week.

Thanks,
Matt

**Comment by mharista** [comment]
Hi @bobbywatson3,

I have a test environment set up and have been able to recreate the issue. You can currently increase the timeout by adding the parameter to the connection call as shown below. The default is 60 seconds. I am recreating the failure by dropping the timeout value to 10.

eapi = pyeapi.connect(transport='http', host='172.20.1.6', username='user', password='pass', timeout=120)

I'm currently testing some options for better error reporting. Can you try increasing the timeout as shown above and let me know if that resolves your issue?

Thanks,
Matt

**Comment by mharista** [comment]
@bobbywatson3 you can also verify the exception being raised is the result of a timeout by checking the value of node.socket_error after the exception is raised. Example after I set the timeout to 10 is below.

>>> node = pyeapi.connect(transport='http', host='host', username='user', password='pass', timeout=10)
>>> node.transport.timeout
10
>>> pp(node.execute(commands=cmds1, encoding='json'))
No handlers could be found for logger "pyeapi.eapilib"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyeapi/eapilib.py", line 490, in execute
    response = self.send(request)
  File "pyeapi/eapilib.py", line 423, in send
    raise ConnectionError(str(self), 'unable to connect to eAPI')
pyeapi.eapilib.ConnectionError: unable to connect to eAPI
>>> node.socket_error
timeout('timed out',)

**Comment by bobbywatson3** [comment]
Thanks I'll give that a shot. 

I do not think that the exception text is helpful however. The exception specifically states that it was unable to connect to eAPI, which is false. It was able to connect initially, but then timed out waiting for a response to the command that was transmitted.

**Comment by mharista** [comment]
@bobbywatson3 I agree. I'm planning to update the exception to report a command timed out for this case.
