### ISSUE TITLE
Exception Raised if wrong details

### ISSUE THREAD

**Issue by adminahmad** [arista-eosplus/pyeapi#140]
Hello
If wrong details is supplied the pyeapi lib will raise and error

as it get wrong 
like 
b'Unable to authenticate user: Bad username/password combination'
the code that has the problem

```
if not type(response_content) == str:
                # For Python 3.x - decode bytes into string
                response_content = response_content.decode()
            decoded = json.loads(response_content)
            _LOGGER.debug('eapi_response: %s' % decoded)
```

my suggested fix

```
 try:
                    decoded = json.loads(response_content)
                except:
                    pass
```

**Comment by mharista** [comment]
Hi @adminahmad,

Could you provide a code snippet that demonstrates the issue you are having? Can you also expand on what you mean when you say "wrong details" are supplied?

Thanks,
Matt

**Comment by dlyssenko** [comment]
@adminahmad , It's been a while w/o no reply. The handling of the incorrect credentials is correct - if user wants to handle failure he/she has to enclose it into try/except block. The subsequent code (the snippet you posted) in such case won't get executed.

The potential JSON decoding issue (which you imply to bypass) is an unexpected behavior, which normally should fail (i.e. if `response_content` is ill-formed JSON, then it should fail here - why handling it furhter?).

I'll close this issue, however if you feel like you have a strong case to present - please feel free to reach us out with your examples.
