### ISSUE TITLE
Connection failure due to bad username/password fails to report reason

### ISSUE THREAD

**Issue by jeremyschulman** [arista-eosplus/pyeapi#153]
Upon attempting to connect with bad credentials, a ConnectionError is reported with the following information:

`````
pyeapi.eapilib.ConnectionError: unable to connect to eAPI
`````
There could be a few reasons for this, I would imaging, for example, the device not being configured / enabled for eAPI.

But the actual device response_content value in the underlying eapilib.py file, when debugged, provides the root cause:

````
(Pdb) pp(response_content)
'Unable to authenticate user: Bad username/password combination'
````

It would be very helpful if this information (response_content) could be bubbled up as an additional argument value to the ConnectionError.

Thank you!

**Comment by mharista** [comment]
Hi @jeremyschulman,

I just added this functionality recently via #152.

**Comment by jeremyschulman** [comment]
@mharista - excellent, thank you!  When do you anticipate the develop branch being merged, and a new release being made available via PyPi?

**Comment by mharista** [comment]
@jeremyschulman I do not have any plans for a release in the near future but I can bring this up internally and update you afterwards.

**Comment by mharista** [comment]
Hi @jeremyschulman,

I am planning to do another release early next year after closing out the remaining PR's that are open.

**Comment by jeremyschulman** [comment]
Fantatsic, thank you for the update!

**Comment by mharista** [comment]
Hi @jeremyschulman 

A new release 0.8.2 has been added to pypi that includes the fix for this issue.
