### ISSUE TITLE
Uncaught Exceptions from HTTPConnection.getresponse

### ISSUE THREAD

**Issue by dcarrier** [arista-eosplus/pyeapi#167]
https://github.com/arista-eosplus/pyeapi/blob/96a74faef1fe3bd79c4e900aed29c9956a0587d6/pyeapi/eapilib.py#L391

The library does not currently catch exceptions raised from the HTTPConnection class in http/client.py. 
To reproduce the error: 

1. Add an ACL blocking the eAPI port

```
ip access-list no-api-for-you
   10 deny ip any any

management api http-commands
   no shutdown
   !
   vrf default
      ip access-group no-api-for-you
!
```

2. Create a EapiConnection object

```
self.api = pyeapi.connect(
                transport=self.transport,
                port=self.port,
                host=self.host,
                username=self.username,
                password=self.password,
            )

```
3. Try to execute a command

`self.api.execute(['show lldp neighbors'])`

```
Traceback (most recent call last):
  File "/Users/dcarrier/Documents/codethethings/python/bitbucket.stackpath.net/REL/platform-utils/.env/lib/python3.6/site-packages/pyeapi/eapilib.py", line 390, in send
    response = self.transport.getresponse()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
```

**Comment by dlyssenko** [comment]
Hi @dcarrier, throwing exception by pyeapi is a valid behavior and it's user responsibility to handle such exceptions.
In your case you'd need to wrap your call into `try` - `except` block, like this:
```
try
   self.api.execute(['show lldp neighbors'])
except pyeapi.eapilib.ConnectionError as e:
   # handle exception ...
```

_Note: by default `pyeapi` is configured to print `http.client` tracebacks (shall any occur), which inevitably will print the traceback in your case (despite catching `ConnectionError`). You may want to disable such behavior with this command: `pyeapi.eapilib._LOGGER.setLevel( logging.CRITICAL )`, then the intercept will occur silently. Ror more details about disabling http tracebacks, see issue #229_

with this I'm closing this issue, let me know if any questions.
