### ISSUE TITLE
Update to work with old and new CLI syntax

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/pyeapi#171]
https://www.arista.com/en/support/advisories-notices/fieldnotices/7097-field-notice-39

**Comment by bewing** [comment]
Is there a status on this, or is it expected that downstream tools deal with this in another way?

**Comment by devrobo** [comment]
We hope to get to this in November.

**Comment by yadavshubhanshu** [comment]
Is there any ETA on this ? We were planning to shift to EOS 4.23 soon and it would be good to get this library supported for it.

**Comment by andriirr** [comment]
This has been addressed in 0.8.3 release (#182 )
