### ISSUE TITLE
Performance improvement for sending requests

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/pyeapi#18]
The Capi team discovered a 40 ms delay that happens on subsequent requests to a keepalive connection between when the client sends its headers and when it sends the rest of the data (this is due to an interaction of a deferred ACK on the server side and nagle's algorithm on the client side). This can be addressed by sending the data in the endheaders request.

It would also be nice to have a benchmark of the pyeapi library so that we can see the performance improvement of this change.

**Comment by phil-arista** [comment]
I think this might already be factored into the code. See: https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/eapilib.py#L364

**Comment by phil-arista** [comment]
Fixed with https://github.com/arista-eosplus/pyeapi/pull/74
