### ISSUE TITLE
How to Log out after request is done?

### ISSUE THREAD

**Issue by selvam33** [arista-eosplus/pyeapi#185]
Greetings, 

Is there is a way to disconnect the session once we have completed the request?

since the "exit" command is working.

Thanks !!!

**Comment by andriirr** [comment]
Current implementation of pyeapi rely on http/https transport protocol. In particular, once configuration pushed o the switch, it carried in POST request. Underlay transport abstraction defined in eapilib is responsible for managing such a connection, including closing it (see [here](https://github.com/arista-eosplus/pyeapi/blob/052b500b1e382a96000928e58aaebbb35ba87bcf/pyeapi/eapilib.py#L309))

**Comment by selvam33** [comment]
Below is the script i am using to connect and exit from the request. But I am still able to connect even though i have done exit. Am i doing something wrong?

node = pyeapi.connect(transport="https", host="host", username=UN, password=PW, port=None)
interface = node.execute(["show interfaces status notconnect disabled"])
pyeapi.eapilib.EapiConnection.request(self=node, commands="exit")

**Comment by andriirr** [comment]
What exactly do you mean by existing, what exactly you expect to happen after your request?

**Comment by andriirr** [comment]
If I understood correctly, you are referring to the activity of terminating TCP/HTTPS connection made by pyeapi client. This connection is closed automatically once request is completed. Thats is what I meant in the previous message. You can validate this by doing packet capture for calls made by pyeapi or checking netstat outputs.

Next output was collected while calling 'show tech-support' through pyeapi. 
New TCP session created.

[arista@cvx ~]$ netstat -an | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN
tcp6       0      0 10.XX.XXX.XXX:443       10.XX.XXX.YY:50356     ESTABLISHED

Once request executed, connection is gone

[arista@cvx ~]$ netstat -an | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN

**Comment by selvam33** [comment]
Thanks, I will check this out.

**Comment by dlyssenko** [comment]
Given Andrii already answered the question (eapi is relying on stateless REST messaging, hence closes connection after every eapi transaction), I'm closing this question.
