### ISSUE TITLE
VLAN config parsing fails if VLANs are grouped together

### ISSUE THREAD

**Issue by yellowcrescent** [arista-eosplus/pyeapi#197]
Hello! While testing pyeapi, I discovered an issue in the api.vlans module: if VLANs are grouped together in the full config output (eg. `vlan 509-510`), then config parsing fails. This only seems to happen if setting a `name` attribute for a group of VLANs.

Example configuration that causes failure (output captured directly from vlans.config)
```
vlan 509-510
   name customer-5b32e5S2
   mac address learning
   state active
   mac address forwarding unicast miss action flood
   mac address forwarding multicast miss action flood
   trunk group 5b32e5S2
!
```

When this configuration is present, attempting to call `vlans.get(509)` or `vlans.get(510)` will return `None`, since the regex in `vlans.get()` doesn't support range-based definitions.

If multiple VLANs are using their default (unique) `name`, then config parsing works as expected:
```
vlan 509
   name VLAN0509
   mac address learning
   state active
   mac address forwarding unicast miss action flood
   mac address forwarding multicast miss action flood
   trunk group 5b32e5S2
!
vlan 510
   name VLAN0510
   mac address learning
   state active
   mac address forwarding unicast miss action flood
   mac address forwarding multicast miss action flood
   trunk group 5b32e5S2
!
```

Switch model/version info:
```
Arista DCS-7060CX-32S-R
Hardware version:      12.00
Software image version: 4.23.4.2M
```

I can workaround the issue for now by applying a suffix to the names (eg. `customer-5b32e5S2-509`) to ensure they are unique, but would rather keep the VLANs grouped together so that the switch configuration is easier to view.

Thanks!

**Comment by eqx311** [comment]
StpTopology: %SPANTREE-4-TOPOLOGY_LIMIT_EXCEEDED: No topology created for VLAN XXX. The maximum number of supported topologies is 509. The number of configured VLANs is XXX more than the number of allowed topologies

**Comment by ldn-softdev** [comment]
Hi yellowcrescent,
in your case, the api call must look like: `vlans.get('509-510')` - then it'll return the respective config block.
the API's parsing is written/structured such way that it's not aware of VLANs as entities, it rather performs a literal lookup/search.

Let me know if that addresses your issue.

**Comment by ldn-softdev** [comment]
However, what I notice is that in case if such vlan grouping (ranges, enumerations) present in the config, then `vlans.getall()` won't work correctly either. So, I'm going to post a quick fix for that issue
