### ISSUE TITLE
config modules don't raise error if the credentials are incorrect

### ISSUE THREAD

**Issue by noredistribution** [arista-eosplus/pyeapi#198]
For example when trying to create vlans if the credentials are incorrect we only print `False`

e.g. if you do something like this

```
import pyeapi

connect = pyeapi.connect_to("leaf1-DC1")
print(connect)

vlan_ids = ["10","20","30","40","50"]

for vlan in vlan_ids:
    connect.api('vlans').create(vlan)
    print(f"Creating vlan {vlan}")
```
that doesn't raise any error; if you print the connect statement then it prints `False`, wherease if you use `get` or `getall`functions that raises the correct error

```
  File "/usr/local/lib/python3.7/dist-packages/pyeapi/eapilib.py", line 455, in send
    response_content))
pyeapi.eapilib.ConnectionError: Unauthorized. b'Unable to authenticate user: Bad username/password combination'
```
seems like we don't raise error here: https://github.com/arista-eosplus/pyeapi/blob/9d90ad80cb58fe9189b0a721a05f37a4141b9785/pyeapi/api/abstract.py#L126

**Comment by ldn-softdev** [comment]
let me check the idea behind handling exception due to `ConnectionError ` inband and I'll get back to this one.
