### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DavidVentura** [arista-eosplus/pyeapi#219]
Hi
Is anything blocking a new release? I'm interested in not maintaining my fork anymore -- if there's a pending task or so that you need help with to get a release out, I can help you!

**Comment by mharista** [comment]
Hi @DavidVentura 

We will do some internal discussion around this in the next day or so. You mentioned that you are maintaining a fork of pyeapi. I am curious if whatever changes/updates you have in your fork are already included in the develop branch of pyeapi?

**Comment by DavidVentura** [comment]
Yep, they are currently in develop (#216, #214)

**Comment by ktbyers** [comment]
Re-upping this...I need some of the PY3.10 support features for NAPALM so it would be nice to have a new release.

**Comment by dlyssenko** [comment]
I'm working towards a new release, but due to switching from python2 to python3 here at arista, many of  unit/system tests require update - it’s quite a bit of work.

**Comment by ktbyers** [comment]
@dlyssenko No worries...I actually just realized I can work around the SSL PY3.10 issue entirely inside of NAPALM so it definitely became less pressing.

**Comment by dlyssenko** [comment]
@ktbyers  ktbyers could you share what SSL issue? I recently merged a PR where I allowed passing SSL context to the pyeapi now. Is that the one, or you meant something else?

**Comment by ktbyers** [comment]
@dlyssenko The PY3.10 SSL handshake issue (due to tighter security defaults i.e. the same one you referenced above for the SSL context).

https://github.com/napalm-automation/napalm/issues/1731

But as I mentioned above, we can work around it in NAPALM without any fix in pyeapi...so I am much less concerned about a pyeapi release.

**Comment by dlyssenko** [comment]
closing this one: the submitter found an acceptable w/a, plus the works towards the new release are underway.
