### ISSUE TITLE
pyeapi/api/ipinterfaces.py suggestion

### ISSUE THREAD

**Issue by gregbo** [arista-eosplus/pyeapi#253]
IMO, it would be helpful if you added some pointers to RFCs 791 and 8200 that explain the range of allowable MTUs.  This range differs from what I have seen in some [Arista EOS documentation on configuring interface MTUs](https://www.arista.com/en/um-eos/eos-support-for-l3-mtu-on-7280r37500r37800r3#concept_cht_bht_vnb).

**Comment by dlyssenko** [comment]
Hi @gregbo, where do you suggest to add it in the documentation, could you provide a pointer? (or even better - file a PR).

**Comment by dlyssenko** [comment]
addressed with PR #257
