### ISSUE TITLE
pyeapi/eapilib.py suggestion

### ISSUE THREAD

**Issue by gregbo** [arista-eosplus/pyeapi#254]
For readability and maintainability, I'd suggest changing the version comparison in https_connection_factory() to:

`if sys.version_info < (2, 7, 9):`

similarly to how it is done in other parts of the code.

**Comment by dlyssenko** [comment]
the `develop` branch has already dropped all versions below 3.6, thus that check could be removed entirely as irrelevant. The next pyeapi release will be python3 only.

**Comment by dlyssenko** [comment]
closing this one - all the outdated version checks have been removed with PR #260
