### ISSUE TITLE
vlan api fails to import

### ISSUE THREAD

**Issue by agehring** [arista-eosplus/pyeapi#27]
>>> vlans = node.api('vlans')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyeapi/client.py", line 656, in api
  File "build/bdist.macosx-10.10-intel/egg/pyeapi/utils.py", line 116, in load_module
ImportError: unable to import module pyeapi.api.vlans

**Comment by phil-arista** [comment]
Hello,
How did you construct your node object? 

Like so?
```
import pyeapi
node = pyeapi.connect_to('connection')
```

Also, what version of pyeapi and python?

Thanks

**Comment by agehring** [comment]
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeapi
>>> node = pyeapi.connect_to('HQ-Core-01')
>>> vlans = node.api('vlans')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyeapi/client.py", line 656, in api
  File "build/bdist.macosx-10.10-intel/egg/pyeapi/utils.py", line 116, in load_module
ImportError: unable to import module pyeapi.api.vlans
>>> print pyeapi.__version__
develop

**Comment by phil-arista** [comment]
Ok, so you're running pyeapi from source I gather.

If you run from the cloned git repo: 
```
git rev-parse HEAD
```
Do you get (just so I know where in the develop branch you are):
``417021f45d1661c83f52d85ccbfca202d48861d2``

Did you install pyeapi from pip via?:
```
pip install -e /path/to/pyeapi
```

Sorry for all of the questions.  I don't see this in my testing and I confirmed on a similar platform. 

Thanks!

**Comment by agehring** [comment]
I originally installed from pip

`pip install pyeapi`

And was getting the error, so I cloned the repo and did a python install

`python setup.py install`

results of git rev-parse

417021f45d1661c83f52d85ccbfca202d48861d2

**Comment by phil-arista** [comment]
If you'd like, we can troubleshoot this live?  Send an email to eosplus-dev@arista.com and I'll setup a gotomeeting.  Sorry about the inconvenience!

**Comment by phil-arista** [comment]
The issue was related to PYTHONPATH not being set.

One possible resolution:

Install cloned pyeapi:
```
sudo pip install -e /path/to/pyeapi
```

Then set PYTHONPATH to this same path.
