### ISSUE TITLE
Documentation for modules broken / missing?

### ISSUE THREAD

**Issue by ee-github** [arista-eosplus/pyeapi#294]
I was looking to get basic info on currently implemented api modules, but it appears the relevant docs sections is currently broken?   https://pyeapi.readthedocs.io/en/master/modules.html

This file refers to directories that don't seem to exist in /docs:  https://github.com/arista-eosplus/pyeapi/blob/develop/docs/modules.rst

```
   client_modules/_list_of_modules
   api_modules/_list_of_modules
```

Related:  I noticed that this file in /docs doesn't seem to be reflected anywhere on the readthedocs.io site:  https://github.com/arista-eosplus/pyeapi/blob/develop/docs/configsessions.rst

**Comment by dlyssenko** [comment]
Hi Oleg, thanks for catching this. I have already fixed that once, but it seems the doc build is failing again. I'll take a look and will fix it asap.

**Comment by tonybourkesdnpros** [comment]
Yup, came here to say the same thing.

**Comment by dlyssenko** [comment]
The "modules" documentation section has been fixed now for `develop` branch https://pyeapi.readthedocs.io/en/develop/ with PR #300.
The `master` branch will be fixed automatically once the new release is published
