### ISSUE TITLE
Enhancement - Allow creation of Ethernet Sub-Interfaces

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/pyeapi#30]
These are slightly different from regular Ethernet interfaces in that they are logical and can be added/removed.

failed: [do324] => (item={'enable': True, 'name': 'Ethernet50/1.100'}) => {"failed": true, "item": {"enable": true, "name": "Ethernet50/1.100"}}
msg: creating Ethernet interfaces is not supported

From interfaces.py:

def create(self, name):
        """Creating Ethernet interfaces is currently not supported
        Args:
            name (string): The interface name
        Raises:
            NotImplementedError: creating Ethernet interfaces is not supported
        """
        raise NotImplementedError('creating Ethernet interfaces is '
                                  'not supported')

**Comment by phil-arista** [comment]
In what case does this arise? What associated CLI commands would create the desired output?

**Comment by perimore** [comment]
(config)# interface ethernet 3/1/1.100

This would create sub-interface 3/1/1.100 which can be deleted with the 'no' commands, the same as SVI.

**Comment by chepazzo** [comment]
Is this supported in EOS? I know I've requested before for this feature, but it doesn't seem to work on 4.14.5F:

```
arista-vm1(config)#interface Ethernet1.100
% Invalid input
arista-vm1(config)#
```

**Comment by yenlinsu** [comment]
Hi Mike, this is supported starting in 4.15

**Comment by phil-arista** [comment]
Thanks @yenlinsu!

With regard to the enhancement, it should be relatively painless to implement, we just need to determine the best way to deal with min eos version.
