### ISSUE TITLE
client.py 'def enable' returned dictionary key inconsistency

### ISSUE THREAD

**Issue by yenlinsu** [arista-eosplus/pyeapi#35]
in client.py 'def enable', line 588, the returned key is "response" if the encoding is enforced (strict=True).

in line 595, the returned key is "result" if the encoding is not enforced.

Wouldn't this create difficulties when writing code to parse the output, that the user needs to worry about when to look for "response" and when to look for "result"?

**Comment by phil-arista** [comment]
Good catch Allen. We should be able to get this fixed in the upcoming release due early october

**Comment by phil-arista** [comment]
For this upcoming release we'll continue to return the incorrect key to not break existing scripts and add the correct key.  In the future we'll remove the incorrect key.

**Comment by phil-arista** [comment]
Release Note:
The key that's supposed to be returned is ``result`` but instead the method formerly returned the key ``response``.  For now, both ``response`` and ``result`` will be returned with the same data, but ``response`` will be removed in a future release.
