### ISSUE TITLE
Simplifying connect() function when not using .eapi.conf

### ISSUE THREAD

**Issue by ktbyers** [arista-eosplus/pyeapi#37]
I am using pyeapi in a context where I want arguments like username/password to come from the Ansible inventory (potentially from Ansible's vault) and not from .eapi.conf.

I look into the code a bit and was messaging with Ryan Madsen of Arista. connect_to function looks to be hard-coded to use the arguments from the .eapi.conf file. I then tried to just use the connect() method.

eapi_conn = pyeapi.connect(transport='https', host='1.1.1.1', username='admin', password='passw', port=8443)

After I did this, I would get the following message when I tried to execute my Ansible playbook. 

AttributeError: 'HttpsEapiConnection' object has no attribute 'enable'

In other words, I expected that I would have the same methods available to me as I had with the connect_to() call. I looked at what you did with connect_to() call and I could see that you were creating a Node() instance.

Ryan then pointed out I could do the following:
> cnxn = pyeapi.client.connect(transport="https", host="lf240", username="admin", password="foo")
> node = pyeapi.client.Node(cnxn)

I think it would be better if you did one of the following:

1. Have the connect() method return a Node object. I don't know if there are uses of connect() without creating a Node object (i.e. whether doing this breaks backwards compatibility). If backwards compatibility is an issue, then you could add a function parameter like 'return_node=False' and have it default to False so that the behavior only changes if someone calls it with the new argument).

2. Update the package __init__.py file and __all__ list to add the Node class. This would make it clearer that you potentially intended users to directly use this class (and then add a message to the docstring for the connect() function on how connect can be used with the Node class).

**Comment by phil-arista** [comment]
Hi, I'm curious how you're using pyeapi in the context of Ansible.  As you might know we have and ansible role that is based on pyeapi.  In all of those ansible modules we include meta-args that are essentially eapi.conf variables.

Addressing your suggestions:
1. The connect_to method uses connect() as you see here https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/client.py#L741, so we couldn't have connect() return a node object unless of course we expose a new arg like you mentioned (we'll look into this, it's a great idea).

2. Also a great suggestion.

**Comment by ktbyers** [comment]
I am using it as part of a course that I teach. I have an exercise where I
have the students create an Ansible module. Earlier I was having them use
eapilib, but have just updated it to use pyeapi.

With eapilib, I was having the students pass in the connection arguments
(username, password, port, host) from the Ansible inventory file.

I think it does make sense in general, however, to allow arguments to be
passed into connect() somehow and to get a Node object back. Ryan showed me
how to do this with just calling the Node class from inside the 'client.py'
module.



Regards,

Kirk


On Thu, Sep 17, 2015 at 8:36 PM, Philip DiLeo <notifications@github.com>
wrote:

> Hi, I'm curious how you're using pyeapi in the context of Ansible. As you
> might know we have and ansible role that is based on pyeapi. In all of
> those ansible modules we include meta-args that are essentially eapi.conf
> variables.
>
> Addressing your suggestions:
> 1. The connect_to method uses connect() as you see here
> https://github.com/arista-eosplus/pyeapi/blob/develop/pyeapi/client.py#L741,
> so we couldn't have connect() return a node object unless of course we
> expose a new arg like you mentioned (we'll look into this, it's a great
> idea).
>
>    1. Also a great suggestion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arista-eosplus/pyeapi/issues/37#issuecomment-141334698>
> .
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation
