### ISSUE TITLE
Expose specific error messages in eapilib.CommandError

### ISSUE THREAD

**Issue by rmadsen** [arista-eosplus/pyeapi#4]
It would probably be nice to expose the underlying error messages when somebody gets a CommandError. Right now we just show the code and message, but it would be nice to show whatever is in the 'errors' array at `result[-1]['data']['errors']` (if it exists), as those errors are usually the most explanatory. Perhaps they can automatically by joined into a single string—your call.

It would also be nice to store the remainder of the 'data' object in the CommandError (minus the inserted `enable` or `config terminal` commands), so people can see the responses of the other commands run before the error hit.

**Comment by privateip** [comment]
Added the capabilities as you outlined in the issue to provide the inner error message as well as the output from the commands leading up to the error.  Also adds a trace property to the CommandError instance (see below for example).

```
>>> import pyeapi
>>> node = pyeapi.connect_to('veos01')
>>> node.enable(['show hostname', 'show run', 'show version'], strict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/eapi/pyeapi/pyeapi/client.py", line 495, in enable
    responses = self.run_commands(commands, encoding)
  File "/eapi/pyeapi/pyeapi/client.py", line 541, in run_commands
    response = self._connection.execute(commands, encoding)
  File "/eapi/pyeapi/pyeapi/eapilib.py", line 388, in execute
    response = self.send(request)
  File "/eapi/pyeapi/pyeapi/eapilib.py", line 343, in send
    output=_output)
pyeapi.eapilib.CommandError: CLI command 3 of 4 'show run' failed: invalid command
>>>
>>>
>>> node.connection.error.commands
['enable', 'show hostname', 'show run', 'show version']
>>>
>>> node.connection.error
CommandError(u"CLI command 3 of 4 'show run' failed: invalid command",)
>>>
>>> node.connection.error.command_error
u"incomplete token (at token 1: 'run')"
>>>
>>>
>>> import pprint
>>> pprint.pprint(node.connection.error.trace)
[{'command': 'enable', 'output': {}},
 {'command': 'show hostname',
  'output': {u'fqdn': u'QUNBIN9SM0QR2ZPNMTW2OTHHE9NBSBEYX7BBGW6LPBVO77CQ.stormcontrol.net',
             u'hostname': u'QUNBIN9SM0QR2ZPNMTW2OTHHE9NBSBEYX7BBGW6LPBVO77CQ'}},
 {'command': 'show run',
  'output': {u'errors': [u"incomplete token (at token 1: 'run')"]}},
 {'command': 'show version', 'output': None}]
>>>
>>>
```

**Comment by rmadsen** [comment]
Sounds great! Perhaps even go one step further and include `node.connection.error.command_error` in the stringification of CommandError? I think most users won't remember to look at this field, and it usually holds the interesting data. Perhaps we don't want to include it in the stringification of certain error message, but if `error.code == 1000` (general error), then it is definitely more useful to get the actual message.

**Comment by privateip** [comment]
changes committed to v0.1.1

will look to incorporate the message changes into 0.1.2.... opening a new issue to track
