### ISSUE TITLE
set_members in interfaces api

### ISSUE THREAD

**Issue by jedelman8** [arista-eosplus/pyeapi#58]
I'm using the latest ansible module for portchannel and getting the following error:

```
failed: [spine2] => {"failed": true}
msg: set_members() got an unexpected keyword argument 'mode'
failed: [spine1] => {"failed": true}
msg: set_members() got an unexpected keyword argument 'mode'

FATAL: all hosts have already failed -- aborting
```

It looks like `pyeapi` has been updated to support this in the `interfaces` api with the `mode` arg in the `set_members` method, but it's not installing the latest from pip.

That said, I'm also getting an error installing from source.

Thanks,
Jason

**Comment by phil-arista** [comment]
This was due to using ansible-eos from develop without the latest pyeapi.
