### ISSUE TITLE
Minor issues in README.md

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/pyeapi#8]
Line 40-41: 'Each node section must be prefaced by **connection:<name>** where
<name> is the name of the connection.'
   The '<name>' is not displaying on the github webpage that displays the README.md file.

The default values for username, password, enablepwd are not specified.

Line 97 - '## Configuring \[connection:localhost]' section
Might be useful to document the minimum EOS release where the socket transport is supported.

Line 209: ^contributes^contributions

**Comment by privateip** [comment]
Thanks for catching those omissions.   fixed in dfcfcad07271f655ab5f14bbb797eee840ae5aba
