### ISSUE TITLE
Pyeapi support for windows

### ISSUE THREAD

**Issue by lcharor** [arista-eosplus/pyeapi#87]
Customer having trouble in installing pyeapi on windows. The issue is that Python cannot find the syslog module which is a dependency of pyeapi as there does not appear to be one available for Windows.     To make this fully work on Windows, we would need to refactor the code to use the logging module instead of syslog.

Temp solution: We could try the solution at http://stackoverflow.com/questions/25537419/python-import-syslog-on-windows which simply creates stubs for the syslog calls to satisfy the parser but does nothing with any data sent to it.

**Comment by devrobo** [comment]
I think Pull Request 94 will address this issue. Can you please verify that is the case?

**Comment by devrobo** [comment]
Believe PR #94 has addressed the issue.
